AWSTemplateFormatVersion: '2010-09-09'
Description: Voltrix - RDS PostgreSQL (dev/prod)

Parameters:
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 16
    Default: voltrix_prod_password_32chars_ok

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Voltrix RDS subnet group
      SubnetIds:
        - subnet-003d91049e4b0f7f5   # priv-db-1a
        - subnet-070bedfba440ade37   # priv-db-1b
        - subnet-093744e15cb480601   # priv-db-1c

  VoltrixDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: voltrix-db-prod
      DBName: voltrix
      Engine: postgres
      EngineVersion: '15.18'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      MaxAllocatedStorage: 100
      StorageType: gp3
      StorageEncrypted: true
      MasterUsername: voltrix_admin
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - sg-0b6926e090298ec13   # sg-rds-prod
      MultiAZ: false
      BackupRetentionPeriod: 3
      DeletionProtection: false
      PubliclyAccessible: false

  # ElastiCache Redis (single node for now)
  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: voltrix-cache-subnet-prod
      Description: Voltrix Redis subnet group
      SubnetIds:
        - subnet-003d91049e4b0f7f5
        - subnet-070bedfba440ade37

  VoltrixRedis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: voltrix-redis-prod
      CacheNodeType: cache.t3.micro
      Engine: redis
      EngineVersion: '7.0'
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      VpcSecurityGroupIds:
        - sg-0ee7ca35814c3ace5   # sg-redis-prod

Outputs:
  DBEndpoint:
    Value: !GetAtt VoltrixDB.Endpoint.Address
    Export:
      Name: voltrix-db-endpoint-prod

  DBPort:
    Value: !GetAtt VoltrixDB.Endpoint.Port
    Export:
      Name: voltrix-db-port-prod

  RedisEndpoint:
    Value: !GetAtt VoltrixRedis.RedisEndpoint.Address
    Export:
      Name: voltrix-redis-endpoint-prod
