#!/bin/bash
# Voltrix CDN Setup — Cloudflare (replaces CloudFront)
# Run this after you sign up at cloudflare.com and add your domain

set -e

echo "╔══════════════════════════════════════════════════════╗"
echo "║     Voltrix CDN — Cloudflare Setup Guide             ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "CloudFront is blocked on new AWS accounts."
echo "Cloudflare is FREE, has a Nairobi PoP (closest to Uganda),"
echo "and works immediately — no verification needed."
echo ""
echo "Steps:"
echo ""
echo "1. Sign up free at https://cloudflare.com"
echo ""
echo "2. Add your domain (e.g. voltrix.ug or voltrix.app)"
echo "   - Cloudflare will give you nameservers"
echo "   - Update your domain registrar to use those nameservers"
echo ""
echo "3. In Cloudflare DNS, add these records:"
echo ""
echo "   Type  Name    Value"
echo "   A     @       (your server IP)"  
echo "   CNAME api     voltrix-alb-prod-1152339653.eu-west-1.elb.amazonaws.com"
echo "   CNAME www     voltrix-alb-prod-1152339653.eu-west-1.elb.amazonaws.com"
echo ""
echo "4. Enable Cloudflare proxy (orange cloud) on all records"
echo "   This gives you: DDoS protection, SSL, CDN, all free"
echo ""
echo "5. In Cloudflare SSL/TLS settings:"
echo "   Set mode to 'Flexible' initially"
echo ""
echo "6. Update voltrix-platform/backend/.env:"
echo "   CLOUDFRONT_DOMAIN=https://yourdomain.com"
echo ""
echo "7. Update AWS secret:"
echo "   aws secretsmanager put-secret-value \\"
echo "     --secret-id voltrix/cloudfront_domain \\"
echo "     --secret-string https://yourdomain.com \\"
echo "     --region eu-west-1"
echo ""
echo "For video files (S3) — add S3 bucket as Cloudflare R2 origin"
echo "or use S3 presigned URLs directly (works without CDN for launch)"
echo ""
echo "ALB DNS: voltrix-alb-prod-1152339653.eu-west-1.elb.amazonaws.com"
echo "Account: 211427342512 | Region: eu-west-1"
